name: Build and Deploy to DigitalOcean

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  REGISTRY: registry.digitalocean.com/dev-cr
  IMAGE_NAME: digitaloceanaiautomation
  DROPLET_NAME: ubuntu-s-1vcpu-1gb-nyc1-01

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
    - name: Log in to DigitalOcean Container Registry
      run: doctl registry login --expiry-seconds 1200
    
    - name: Set environment variables
      run: |
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          echo "DEPLOY_ENV=prod" >> $GITHUB_ENV
          echo "CONTAINER_NAME=digitaloceanaiautomation-prod" >> $GITHUB_ENV
          echo "CONTAINER_PORT=80" >> $GITHUB_ENV
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
        elif [ "${{ github.ref }}" = "refs/heads/dev" ]; then
          echo "DEPLOY_ENV=dev" >> $GITHUB_ENV
          echo "CONTAINER_NAME=digitaloceanaiautomation-dev" >> $GITHUB_ENV
          echo "CONTAINER_PORT=8080" >> $GITHUB_ENV
          echo "IMAGE_TAG=dev" >> $GITHUB_ENV
        fi
        echo "Deploying to environment: $DEPLOY_ENV"
        echo "Container name: $CONTAINER_NAME"
        echo "Container port: $CONTAINER_PORT"
    
    - name: Clean up existing repository before build
      run: |
        echo "Checking repository status..."
        
        # List all repositories first
        echo "Current repositories in dev-cr registry:"
        doctl registry repository list-v2 dev-cr || echo "No repositories found"
        
        # Proceed only if digitaloceanaiautomation is the only repository or none exist
        REPO_COUNT=$(doctl registry repository list-v2 dev-cr --format Name --no-header 2>/dev/null | wc -l)
        if [ "$REPO_COUNT" -gt 1 ]; then
          echo "❌ ERROR: Too many repositories ($REPO_COUNT) - exceeds free tier limit of 1"
          echo "Cleanup failed. Current repositories:"
          doctl registry repository list-v2 dev-cr
          exit 1
        elif [ "$REPO_COUNT" -eq 1 ]; then
          EXISTING_REPO=$(doctl registry repository list-v2 dev-cr --format Name --no-header 2>/dev/null)
          if [ "$EXISTING_REPO" != "digitaloceanaiautomation" ]; then
            echo "❌ ERROR: Wrong repository exists: $EXISTING_REPO"
            echo "Expected 'digitaloceanaiautomation' or no repositories"
            exit 1
          else
            echo "✅ Target repository 'digitaloceanaiautomation' exists - proceeding with tag update"
          fi
        else
          echo "✅ No repositories found - will create 'digitaloceanaiautomation' on first push"
        fi
        
        echo "Repository state validated. Ready to build and deploy."
    
    - name: Build Docker image
      run: |
        docker build -t $REGISTRY/$IMAGE_NAME:$GITHUB_SHA .
        docker build -t $REGISTRY/$IMAGE_NAME:${{ env.IMAGE_TAG }} .
    
    - name: Push image to DigitalOcean Container Registry
      run: |
        # Validate credentials and authentication before pushing
        echo "Validating DigitalOcean authentication..."
        
        # Check if we're logged into the registry
        if ! docker info | grep -q "registry.digitalocean.com"; then
          echo "Warning: Not logged into DigitalOcean registry, attempting re-login..."
          doctl registry login --expiry-seconds 1200
        fi
        
        # Verify doctl authentication
        echo "Checking doctl authentication..."
        if ! doctl auth list | grep -q "default"; then
          echo "Error: doctl authentication failed"
          exit 1
        fi
        
        # Test registry access by listing repositories
        echo "Testing registry access..."
        if ! doctl registry repository list-v2 dev-cr >/dev/null 2>&1; then
          echo "Error: Cannot access DigitalOcean Container Registry"
          echo "Please check DIGITALOCEAN_ACCESS_TOKEN secret"
          exit 1
        fi
        
        # Verify we have the built images locally
        echo "Checking local images..."
        if ! docker images | grep -q "$REGISTRY/$IMAGE_NAME"; then
          echo "Error: Built images not found locally"
          exit 1
        fi
        
        # Now attempt the push with better error handling
        echo "Authentication validated. Pushing images to registry..."
        
        echo "Pushing SHA-tagged image..."
        if ! docker push $REGISTRY/$IMAGE_NAME:$GITHUB_SHA; then
          echo "Failed to push SHA-tagged image"
          echo "Registry status:"
          doctl registry repository list-v2 dev-cr
          exit 1
        fi
        
        echo "Pushing environment-specific image..."
        if ! docker push $REGISTRY/$IMAGE_NAME:${{ env.IMAGE_TAG }}; then
          echo "Failed to push environment-specific image"
          echo "Registry status:"
          doctl registry repository list-v2 dev-cr
          exit 1
        fi
        
        echo "Push completed successfully!"
        echo "Final registry status:"
        doctl registry repository list-v2 dev-cr
    
    - name: Validate SSH Key before deployment
      run: |
        echo "Validating SSH key configuration..."
        
        # Check if SSH key secret is set and not empty
        if [ -z "${{ secrets.DROPLET_SSH_KEY }}" ]; then
          echo "Error: DROPLET_SSH_KEY secret is empty or not set"
          echo "Please check GitHub repository secrets"
          exit 1
        fi
        
        # Check if SSH key starts with proper format
        SSH_KEY_START=$(echo "${{ secrets.DROPLET_SSH_KEY }}" | head -1)
        if [[ ! "$SSH_KEY_START" =~ ^-----BEGIN.*(PRIVATE KEY|RSA PRIVATE KEY|OPENSSH PRIVATE KEY)-----$ ]]; then
          echo "Error: SSH key does not appear to be in correct format"
          echo "Expected format: -----BEGIN [TYPE] PRIVATE KEY-----"
          echo "Found: $SSH_KEY_START"
          exit 1
        fi
        
        # Check if DROPLET_HOST is set
        if [ -z "${{ secrets.DROPLET_HOST }}" ]; then
          echo "Error: DROPLET_HOST secret is empty or not set"
          exit 1
        fi
        
        # Check if DROPLET_USERNAME is set
        if [ -z "${{ secrets.DROPLET_USERNAME }}" ]; then
          echo "Error: DROPLET_USERNAME secret is empty or not set"
          exit 1
        fi
        
        echo "SSH key validation passed!"
        echo "Host: ${{ secrets.DROPLET_HOST }}"
        echo "Username: ${{ secrets.DROPLET_USERNAME }}"
        echo "SSH Key format: Valid"
    
    - name: Deploy to DigitalOcean Droplet
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          # Configure doctl and login to registry (doctl and docker should already be installed)
          doctl auth init --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          doctl registry login --expiry-seconds 1200
          
          # Check current running containers before cleanup
          echo "Current running containers before cleanup:"
          docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}" || echo "No containers running"
          
          # Stop and remove existing containers for this environment only
          echo "Cleaning up existing containers for ${{ env.DEPLOY_ENV }} environment..."
          docker stop ${{ env.CONTAINER_NAME }} || true
          docker rm ${{ env.CONTAINER_NAME }} || true
          
          # Legacy cleanup (can be removed after a few deployments)
          docker stop digitaloceanaiautomation || true
          docker rm digitaloceanaiautomation || true
          docker stop fastapi-app || true
          docker rm fastapi-app || true
          docker stop fastapi-docker || true
          docker rm fastapi-docker || true
          
          # Check containers after cleanup
          echo "Containers after cleanup:"
          docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}" || echo "No containers running"
          
          # Pull and run new image
          echo "Pulling image for ${{ env.DEPLOY_ENV }} environment..."
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          
          echo "Starting new container: ${{ env.CONTAINER_NAME }}..."
          docker run -d --name ${{ env.CONTAINER_NAME }} -p ${{ env.CONTAINER_PORT }}:8000 --restart unless-stopped ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          
          # Verify container is running and show detailed status
          echo "Final container status:"
          docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"
          
          # Show specific container details if running
          if docker ps | grep -q ${{ env.CONTAINER_NAME }}; then
            echo "✓ ${{ env.CONTAINER_NAME }} container is running successfully"
            echo "Container details:"
            docker inspect ${{ env.CONTAINER_NAME }} --format "{{.State.Status}} - {{.NetworkSettings.Ports}}"
            echo "Access URL: http://147.182.214.146:${{ env.CONTAINER_PORT }}"
          else
            echo "✗ ${{ env.CONTAINER_NAME }} container is NOT running"
            echo "Container logs:"
            docker logs ${{ env.CONTAINER_NAME }} || echo "No logs available"
            exit 1
          fi
          
          # Clean up old images
          echo "Cleaning up old images..."
          docker image prune -f